#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb'; rescue LoadError; end
begin; require 'k8s.io/apimachinery/pkg/runtime/generated.pb'; rescue LoadError; end
begin; require 'k8s.io/apimachinery/pkg/runtime/schema/generated.pb'; rescue LoadError; end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Apis
          module Testapigroup
            module V1
              # forward declarations
              class Carp < ::ProtocolBuffers::Message; end
              class CarpCondition < ::ProtocolBuffers::Message; end
              class CarpList < ::ProtocolBuffers::Message; end
              class CarpSpec < ::ProtocolBuffers::Message; end
              class CarpStatus < ::ProtocolBuffers::Message; end

              class Carp < ::ProtocolBuffers::Message
                set_fully_qualified_name "k8s.io.apimachinery.pkg.apis.testapigroup.v1.Carp"

                optional ::K8s::Io::Apimachinery::Pkg::Apis::Meta::V1::ObjectMeta, :metadata, 1
                optional ::K8s::Io::Apimachinery::Pkg::Apis::Testapigroup::V1::CarpSpec, :spec, 2
                optional ::K8s::Io::Apimachinery::Pkg::Apis::Testapigroup::V1::CarpStatus, :status, 3
              end

              class CarpCondition < ::ProtocolBuffers::Message
                set_fully_qualified_name "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpCondition"

                optional :string, :type, 1
                optional :string, :status, 2
                optional ::K8s::Io::Apimachinery::Pkg::Apis::Meta::V1::Time, :lastProbeTime, 3
                optional ::K8s::Io::Apimachinery::Pkg::Apis::Meta::V1::Time, :lastTransitionTime, 4
                optional :string, :reason, 5
                optional :string, :message, 6
              end

              class CarpList < ::ProtocolBuffers::Message
                set_fully_qualified_name "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpList"

                optional ::K8s::Io::Apimachinery::Pkg::Apis::Meta::V1::ListMeta, :metadata, 1
                repeated ::K8s::Io::Apimachinery::Pkg::Apis::Testapigroup::V1::Carp, :items, 2
              end

              class CarpSpec < ::ProtocolBuffers::Message
                # forward declarations
                class NodeSelectorEntry < ::ProtocolBuffers::Message; end

                set_fully_qualified_name "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpSpec"

                # nested messages
                class NodeSelectorEntry < ::ProtocolBuffers::Message
                  set_fully_qualified_name "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpSpec.NodeSelectorEntry"

                  optional :string, :key, 1
                  optional :string, :value, 2
                end

                optional :string, :restartPolicy, 3
                optional :int64, :terminationGracePeriodSeconds, 4
                optional :int64, :activeDeadlineSeconds, 5
                repeated ::K8s::Io::Apimachinery::Pkg::Apis::Testapigroup::V1::CarpSpec::NodeSelectorEntry, :nodeSelector, 7
                optional :string, :serviceAccountName, 8
                optional :string, :serviceAccount, 9
                optional :string, :nodeName, 10
                optional :bool, :hostNetwork, 11
                optional :bool, :hostPID, 12
                optional :bool, :hostIPC, 13
                optional :string, :hostname, 16
                optional :string, :subdomain, 17
                optional :string, :schedulername, 19
              end

              class CarpStatus < ::ProtocolBuffers::Message
                set_fully_qualified_name "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpStatus"

                optional :string, :phase, 1
                repeated ::K8s::Io::Apimachinery::Pkg::Apis::Testapigroup::V1::CarpCondition, :conditions, 2
                optional :string, :message, 3
                optional :string, :reason, 4
                optional :string, :hostIP, 5
                optional :string, :carpIP, 6
                optional ::K8s::Io::Apimachinery::Pkg::Apis::Meta::V1::Time, :startTime, 7
              end

            end
          end
        end
      end
    end
  end
end
