#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Runtime
          module Schema
          end
        end
      end
    end
  end
end
