#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Util
          module Intstr
            # forward declarations
            class IntOrString < ::ProtocolBuffers::Message; end

            class IntOrString < ::ProtocolBuffers::Message
              set_fully_qualified_name "k8s.io.apimachinery.pkg.util.intstr.IntOrString"

              optional :int64, :type, 1
              optional :int32, :intVal, 2
              optional :string, :strVal, 3
            end

          end
        end
      end
    end
  end
end
