# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/apimachinery/pkg/util/intstr/generated.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "k8s.io.apimachinery.pkg.util.intstr.IntOrString" do
    optional :type, :int64, 1
    optional :intVal, :int32, 2
    optional :strVal, :string, 3
  end
end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Util
          module Intstr
            IntOrString = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.util.intstr.IntOrString").msgclass
          end
        end
      end
    end
  end
end
