# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Unknown" do
    optional :typeMeta, :message, 1, "TypeMeta"
    optional :raw, :bytes, 2
    optional :contentEncoding, :string, 3
    optional :contentType, :string, 4
  end
  add_message "TypeMeta" do
    optional :apiVersion, :string, 1
    optional :kind, :string, 2
  end
end

Unknown = Google::Protobuf::DescriptorPool.generated_pool.lookup("Unknown").msgclass
TypeMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("TypeMeta").msgclass
