# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/apimachinery/pkg/runtime/generated.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "k8s.io.apimachinery.pkg.runtime.RawExtension" do
    optional :raw, :bytes, 1
  end
  add_message "k8s.io.apimachinery.pkg.runtime.TypeMeta" do
    optional :apiVersion, :string, 1
    optional :kind, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.runtime.Unknown" do
    optional :typeMeta, :message, 1, "k8s.io.apimachinery.pkg.runtime.TypeMeta"
    optional :raw, :bytes, 2
    optional :contentEncoding, :string, 3
    optional :contentType, :string, 4
  end
end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Runtime
          RawExtension = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.runtime.RawExtension").msgclass
          TypeMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.runtime.TypeMeta").msgclass
          Unknown = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.runtime.Unknown").msgclass
        end
      end
    end
  end
end
