#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Runtime
          # forward declarations
          class RawExtension < ::ProtocolBuffers::Message; end
          class TypeMeta < ::ProtocolBuffers::Message; end
          class Unknown < ::ProtocolBuffers::Message; end

          class RawExtension < ::ProtocolBuffers::Message
            set_fully_qualified_name "k8s.io.apimachinery.pkg.runtime.RawExtension"

            optional :bytes, :raw, 1
          end

          class TypeMeta < ::ProtocolBuffers::Message
            set_fully_qualified_name "k8s.io.apimachinery.pkg.runtime.TypeMeta"

            optional :string, :apiVersion, 1
            optional :string, :kind, 2
          end

          class Unknown < ::ProtocolBuffers::Message
            set_fully_qualified_name "k8s.io.apimachinery.pkg.runtime.Unknown"

            optional ::K8s::Io::Apimachinery::Pkg::Runtime::TypeMeta, :typeMeta, 1
            optional :bytes, :raw, 2
            optional :string, :contentEncoding, 3
            optional :string, :contentType, 4
          end

        end
      end
    end
  end
end
