#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Api
          module Resource
            # forward declarations
            class Quantity < ::ProtocolBuffers::Message; end

            class Quantity < ::ProtocolBuffers::Message
              set_fully_qualified_name "k8s.io.apimachinery.pkg.api.resource.Quantity"

              optional :string, :string, 1
            end

          end
        end
      end
    end
  end
end
