# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/apimachinery/pkg/api/resource/generated.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "k8s.io.apimachinery.pkg.api.resource.Quantity" do
    optional :string, :string, 1
  end
end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Api
          module Resource
            Quantity = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.api.resource.Quantity").msgclass
          end
        end
      end
    end
  end
end
