#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class Unknown < ::ProtocolBuffers::Message; end
class TypeMeta < ::ProtocolBuffers::Message; end

class Unknown < ::ProtocolBuffers::Message
  set_fully_qualified_name "Unknown"

  optional ::TypeMeta, :typeMeta, 1
  optional :bytes, :raw, 2
  optional :string, :contentEncoding, 3
  optional :string, :contentType, 4
end

class TypeMeta < ::ProtocolBuffers::Message
  set_fully_qualified_name "TypeMeta"

  optional :string, :apiVersion, 1
  optional :string, :kind, 2
end

