// Docker_Server
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
    Description ( "Docker Server Information" )
]
class Docker_Server : CIM_InstalledProduct {


    [ Description ( "Count of containers" ) ]
    uint16 Containers;

    [ Description ( "Docker root directory" ) ]
    string DockerRootDir;

    [ Description ( "Server hostname" ) ]
    string Hostname;

    [ Description ( "Docker driver" ) ]
    string Driver;

    [ Description ( "Current operating status for the Driver" ),
      ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" },
      Values { "Unknown", "Other", "OK", "Degraded", "Stressed", "Predictive Failure", "Error", "Non-Recoverable Error", "Starting", "Stopping", "Stopped", "In Service", "No Contact",  "Lost Communication", "Aborted", "Dormant", "Supporting Entity in Error", "Completed", "Power Mode", "Insufficient Privileges", "Authentication File in Error" }
    ]
    uint16 DriverStatus;

    [ Description ( "Count of Images" ) ]
    uint16 Images;

    [ Description ( "Docker InitPath" ) ]
    string InitPath;

    [ Description ( "Kernel version" ) ]
    string KernelVersion;

    [ Description ( "Current operating status for the MySQL instance" ),
      ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" },
      Values { "Unknown", "Other", "OK", "Degraded", "Stressed", "Predictive Failure", "Error", "Non-Recoverable Error", "Starting", "Stopping", "Stopped", "In Service", "No Contact",  "Lost Communication", "Aborted", "Dormant", "Supporting Entity in Error", "Completed", "Power Mode", "Insufficient Privileges", "Authentication File in Error" }
    ]
    uint16 OperatingStatus;

    [ Description ( "Total installed memory in bytes" ) ]
    uint64 MemTotal;

        [ Description ( "Memory Limit in bytes" ) ]
    uint64 MemLimit;

        [ Description ( "Swap Limit in bytes" ) ]
    uint64 SwapLimit;

        [ Description ( "Number of CPUs" ) ]
    uint16 NCPU;

};

// Docker_Container
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
    Description ( "Docker Container Information" )
]
class Docker_Container : CIM_VirtualComputerSystem {

        [ Description ( "Active Ports for the Container" ) ]
        string Ports;

        [ Description ( "Command for the Container" ) ]
        string Command;

        [ Description ( "Image for the Container" ) ]
        string Image;

        [ Description ( "ID for the Container" ) ]
        string InstanceID;

        [ Description ( "Readwrite size for the Container" ) ]
        string SizeRW;


};


// Docker_ContainerStatistics
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
    Description ( "Docker Container Statistical Information" )
]
class Docker_ContainerStatistics : CIM_StatisticalData {

       [ Description ( "Update time:seconds since 1/1/1970 * 1000 " ) ]
       uint64 updatetime;

    [ Description ( "Network received bytes for the container instance" ) ]
    uint64 NetRXBytes;

        [ Description ( "Network transmitted bytes for the container instance" ) ]
        uint64 NetTXBytes;

        [ Description ( "Network total bytes for the container instance" ) ]
        uint64 NetBytes;

        [ Description ( "Network received kilobytes per second for the container instance" ) ]
        uint32 NetRXKBytesPerSec;

        [ Description ( "Network transmitted kilobytes per second for the container instance" ) ]
        uint32 NetTXKBytesPerSec;

        [ Description ( "Memory cache in megabytes for the container instance" ) ]
        uint32 MemCacheMB;

        [ Description ( "Memory rss in megabytes for the container instance" ) ]
        uint32 MemRSSMB;
       
         [ Description ( "Memory page faults for the container instance" ) ]
        uint16 MemPGFault;

        [ Description ( "Memory major page faultsfor the container instance" ) ]
        uint16 MemPGMajFault;
         

        [ Description ( "Memory page faults per second for the container instance" ) ]
        uint16 MemPGFaultPerSec;

        [ Description ( "Memory major page faults per second for the container instance" ) ]
        uint16 MemPGMajFaultPerSec;

        [ Description ( "Memory swap used in megabytes for the container instance" ) ]
        uint32 MemSwapMB;

        [ Description ( "Memory unvicatable in megabytes for the container instance" ) ]
        uint32 MemUnevictableMB;

        [ Description ( "Memory limit in megabytes for the container instance" ) ]
        uint32 MemLimitMB;

        [ Description ( "Memory swap limit in megabytes for the container instance" ) ]
        uint32 MemSWLimitMB;

        [ Description ( "Percent of the memory limit currently used for the container instance" ) ]
        uint16 MemUsedPct;

        [ Description ( "Percent of the memory swap limit currently used for the container instance" ) ]
        uint16 MemSWUsedPct;

        [ Description ( "CPU (total) used for container instance" ) ]
        uint64 CPUTotal;

        [ Description ( "System CPU (total) used for container instance" ) ]
        uint64 CPUSystem;

        [ Description ( "Percentage of CPU (total) used for container instance" ) ]
        uint16 CPUTotalPct;

        [ Description ( "Percentage of CPU (total) used for container instance" ) ]
        uint16 CPUSystemPct;
       
        [ Description ( "CPU (host) used for host vm" ) ]
        uint64 CPUHost;

};


// Docker_ContainerProcessorStatistics
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
    Description ( "Docker Container Processor Statistical Information" )
]
class Docker_ContainerProcessorStatistics : CIM_StatisticalData {

    [ Description ( "ID of the processor instance" ) ]
    uint16 ProcessorID;

    [ Description ( "CPU used for the processor instance" ) ]
    uint64 CPUTotal;

        [ Description ( "Percentage of CPU used for the processor instance" ) ]
    uint16 CPUTotalPct;


};