// Container_ContainerStatistics
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
	Description ( "Docker Container Statistical Information" )
]
class Container_ContainerStatistics : CIM_StatisticalData
{
	[ Description ( "Update time:seconds since 1/1/1970 * 1000 " ) ]
	uint64 updatetime;

	[ Description ( "Network received bytes for the container instance" ) ]
	uint64 NetRXBytes;

	[ Description ( "Network transmitted bytes for the container instance" ) ]
	uint64 NetTXBytes;

	[ Description ( "Network total bytes for the container instance" ) ]
	uint64 NetBytes;

	[ Description ( "Network received kilobytes per second for the container instance" ) ]
	uint32 NetRXKBytesPerSec;

	[ Description ( "Network transmitted kilobytes per second for the container instance" ) ]
	uint32 NetTXKBytesPerSec;

	[ Description ( "Memory cache in megabytes for the container instance" ) ]
	uint32 MemCacheMB;

	[ Description ( "Memory rss in megabytes for the container instance" ) ]
	uint32 MemRSSMB;

	[ Description ( "Memory page faults for the container instance" ) ]
	uint16 MemPGFault;

	[ Description ( "Memory major page faultsfor the container instance" ) ]
	uint16 MemPGMajFault;
		 
	[ Description ( "Memory page faults per second for the container instance" ) ]
	uint16 MemPGFaultPerSec;

	[ Description ( "Memory major page faults per second for the container instance" ) ]
	uint16 MemPGMajFaultPerSec;

	[ Description ( "Memory swap used in megabytes for the container instance" ) ]
	uint32 MemSwapMB;

	[ Description ( "Memory unvicatable in megabytes for the container instance" ) ]
	uint32 MemUnevictableMB;

	[ Description ( "Memory limit in megabytes for the container instance" ) ]
	uint32 MemLimitMB;

	[ Description ( "Memory swap limit in megabytes for the container instance" ) ]
	uint32 MemSWLimitMB;

	[ Description ( "Percent of the memory limit currently used for the container instance" ) ]
	uint16 MemUsedPct;

	[ Description ( "Percent of the memory swap limit currently used for the container instance" ) ]
	uint16 MemSWUsedPct;

	[ Description ( "CPU (total) used for container instance" ) ]
	uint64 CPUTotal;

	[ Description ( "System CPU (total) used for container instance" ) ]
	uint64 CPUSystem;

	[ Description ( "Percentage of CPU (total) used for container instance" ) ]
	uint16 CPUTotalPct;

	[ Description ( "Percentage of CPU (total) used for container instance" ) ]
	uint16 CPUSystemPct;
	   
	[ Description ( "CPU (host) used for host vm" ) ]
	uint64 CPUHost;

	[ Description ( "Number of bytes read from disk" ) ]
	uint64 DiskBytesRead;

	[ Description ( "Number of bytes written to disk" ) ]
	uint64 DiskBytesWritten;
};

// Container_ImageInventory
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
	Description ( "Docker image inventory data" )
]
class Container_ImageInventory : CIM_ManagedElement
{
	[ Key, Description ( "Image ID" ) ]
	String InstanceID;

	[ Description ( "Image name" ) ]
	String Image;

	[ Description ( "Repository name" ) ]
	String Repository;

	[ Description ( "Image tag" ) ]
	String ImageTag;

	[ Description ( "Host name of Docker host" ) ]
	String Computer;

	[ Description ( "Number of running containers" ) ]
	Uint32 Running;

	[ Description ( "Number of stopped containers" ) ]
	Uint32 Stopped;

	[ Description ( "Number of failed containers" ) ]
	Uint32 Failed;

	[ Description ( "Number of paused containers" ) ]
	Uint32 Paused;

	[ Description ( "Image actual size in MB" ) ]
	string ImageSize;

	[ Description ( "Virtual image size in MB") ]
	string VirtualSize;
};

// Container_DaemonEvent
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
	Description ( "Docker daemon event" )
]
class Container_DaemonEvent : CIM_ManagedElement
{
	[ Key, Description ( "GUID" ) ]
	String InstanceID;

	[ Description ( "Host name of Docker host" ) ]
	String Computer;

	[ Description ( "Timestamp of event" ) ]
	String TimeOfCommand;

	[ Description ( "Event type" ) ]
	String Command;

	[ Description ( "Container ID" ) ]
	String Id;
};

// Container_ContainerInventory
// -------------------------------------------------------------------
[   Version ( "1.0.0" ),
	Description ( "Docker container inventory data" )
]
class Container_ContainerInventory : CIM_ManagedElement
{
	[ Key, Description ( "Container ID" ) ]
	String InstanceID;

	[ Description ( "Time when container was created" ) ]
	String CreatedTime;

	[ Description ( "State of container" ) ]
	String State;

	[ Description ( "Exit code of container" ) ]
	uint32 ExitCode;

	[ Description ( "Time when container started" ) ]
	String StartedTime;

	[ Description ( "Time when container exited" ) ]
	String FinishedTime;

	[ Description ( "Image ID of container" ) ]
	String ImageId;

	[ Description ( "Image name of container") ]
	String Image;

	[ Description ( "Repository name of container") ]
	String Repository;

	[ Description ( "Image tag of container") ]
	String ImageTag;

	[ Description ( "Compose group which contains the container" ) ]
	String ComposeGroup;

	[ Description ( "Host name of container" ) ]
	String ContainerHostname;

	[ Description ( "Host name of Docker host" ) ]
	String Computer;

	[ Description ( "JSON of command run inside container" ) ]
	String Command;

	[ Description ( "JSON of container environment variables" ) ]
	String EnvironmentVar;

	[ Description ( "JSON of container port mappings" ) ]
	String Ports;

	[ Description ( "JSON of container links" ) ]
	String Links;
};