# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/apimachinery/pkg/apis/testapigroup/v1/generated.proto

require 'google/protobuf'

require 'k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb'
require 'k8s.io/apimachinery/pkg/runtime/generated_pb'
require 'k8s.io/apimachinery/pkg/runtime/schema/generated_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "k8s.io.apimachinery.pkg.apis.testapigroup.v1.Carp" do
    optional :metadata, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta"
    optional :spec, :message, 2, "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpSpec"
    optional :status, :message, 3, "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpStatus"
  end
  add_message "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpCondition" do
    optional :type, :string, 1
    optional :status, :string, 2
    optional :lastProbeTime, :message, 3, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
    optional :lastTransitionTime, :message, 4, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
    optional :reason, :string, 5
    optional :message, :string, 6
  end
  add_message "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpList" do
    optional :metadata, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta"
    repeated :items, :message, 2, "k8s.io.apimachinery.pkg.apis.testapigroup.v1.Carp"
  end
  add_message "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpSpec" do
    optional :restartPolicy, :string, 3
    optional :terminationGracePeriodSeconds, :int64, 4
    optional :activeDeadlineSeconds, :int64, 5
    map :nodeSelector, :string, :string, 7
    optional :serviceAccountName, :string, 8
    optional :serviceAccount, :string, 9
    optional :nodeName, :string, 10
    optional :hostNetwork, :bool, 11
    optional :hostPID, :bool, 12
    optional :hostIPC, :bool, 13
    optional :hostname, :string, 16
    optional :subdomain, :string, 17
    optional :schedulername, :string, 19
  end
  add_message "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpStatus" do
    optional :phase, :string, 1
    repeated :conditions, :message, 2, "k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpCondition"
    optional :message, :string, 3
    optional :reason, :string, 4
    optional :hostIP, :string, 5
    optional :carpIP, :string, 6
    optional :startTime, :message, 7, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
  end
end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Apis
          module Testapigroup
            module V1
              Carp = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.testapigroup.v1.Carp").msgclass
              CarpCondition = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpCondition").msgclass
              CarpList = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpList").msgclass
              CarpSpec = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpSpec").msgclass
              CarpStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.testapigroup.v1.CarpStatus").msgclass
            end
          end
        end
      end
    end
  end
end
