# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - ci_dev

pr:
  branches:
    include:
    - ci_dev

pool:
  name: Azure-Pipelines-CI-Test-EO

variables:
  armServiceConnectionName: 'ci-1es-acr-connection'
  subscription: '9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb'
  containerRegistry: 'containerinsightsprod'
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/containerinsights/cidev'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- bash: |
    commit=$(git rev-parse --short HEAD)
    echo "##vso[task.setvariable variable=commit;]$commit"

    datetime=$(date +'%m%d%Y')
    echo "##vso[task.setvariable variable=datetime;]$datetime"

    cd $(Build.SourcesDirectory)/deployment/multiarch-agent-deployment/ServiceGroupRoot/Scripts
    tar -czvf ../artifacts.tar.gz pushAgentToAcr.sh

    cd $(Build.SourcesDirectory)/deployment/arc-k8s-extension/ServiceGroupRoot/Scripts
    tar -czvf ../artifacts.tar.gz ../../../../charts/azuremonitor-containers/ pushChartToAcr.sh

- task: CopyFiles@2
  displayName: "Copy ev2 deployment artifacts"
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/deployment"
    Contents: |
      **/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: CopyFiles@2
  displayName: "Copy ev2 deployment scripts"
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/.pipelines"
    Contents: |
      **/*.sh
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: CopyFiles@2
  displayName: "Copy ev2 deployment scripts"
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/kubernetes"
    Contents: |
      *.yaml
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: CopyFiles@2
  displayName: "Copy ev2 deployment scripts"
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/charts"
    Contents: |
      **/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: CopyFiles@2
  displayName: "Copy ev2 deployment scripts"
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/test/e2e"
    Contents: |
      *.yaml
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: AzureCLI@2
  displayName: "Docker multi-arch linux build"
  inputs:
    azureSubscription: ${{ variables.armServiceConnectionName }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      sudo apt-get update && sudo apt-get -y install qemu binfmt-support qemu-user-static
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      docker buildx create --name testbuilder
      docker buildx use testbuilder

      az --version
      az account show
      az account set -s ${{ variables.subscription }}
      az acr login -n ${{ variables.containerRegistry }}

      if [ "$(Build.Reason)" != "PullRequest" ]; then
        docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ variables.repoImageName }}:$(datetime)-$(commit) -f kubernetes/linux/Dockerfile.multiarch --metadata-file $(Build.ArtifactStagingDirectory)/metadata.json --build-arg IMAGE_TAG=$(datetime)-$(commit) --push .

        docker pull ${{ variables.repoImageName }}:$(datetime)-$(commit)
      else
        docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ variables.repoImageName }}:$(datetime)-$(commit) -f kubernetes/linux/Dockerfile.multiarch --metadata-file $(Build.ArtifactStagingDirectory)/metadata.json --build-arg IMAGE_TAG=$(datetime)-$(commit) .
      fi

- task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
  displayName: 'Generation Task'
  condition: eq(variables.IS_PR, true)
  inputs:
    BuildDropPath: '$(Build.ArtifactStagingDirectory)'
    DockerImagesToScan: 'golang:1.15.14, ubuntu:18.04'

- task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
  displayName: 'Generation Task'
  condition: eq(variables.IS_PR, false)
  inputs:
    BuildDropPath: '$(Build.ArtifactStagingDirectory)'
    DockerImagesToScan: 'golang:1.15.14, ubuntu:18.04, ${{ variables.repoImageName }}:$(datetime)-$(commit)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
