# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto

require 'google/protobuf'

require 'k8s.io/apimachinery/pkg/runtime/generated_pb'
require 'k8s.io/apimachinery/pkg/runtime/schema/generated_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.APIGroup" do
    optional :name, :string, 1
    repeated :versions, :message, 2, "k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionForDiscovery"
    optional :preferredVersion, :message, 3, "k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionForDiscovery"
    repeated :serverAddressByClientCIDRs, :message, 4, "k8s.io.apimachinery.pkg.apis.meta.v1.ServerAddressByClientCIDR"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.APIGroupList" do
    repeated :groups, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.APIGroup"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.APIResource" do
    optional :name, :string, 1
    optional :singularName, :string, 6
    optional :namespaced, :bool, 2
    optional :group, :string, 8
    optional :version, :string, 9
    optional :kind, :string, 3
    optional :verbs, :message, 4, "k8s.io.apimachinery.pkg.apis.meta.v1.Verbs"
    repeated :shortNames, :string, 5
    repeated :categories, :string, 7
    optional :storageVersionHash, :string, 10
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.APIResourceList" do
    optional :groupVersion, :string, 1
    repeated :resources, :message, 2, "k8s.io.apimachinery.pkg.apis.meta.v1.APIResource"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.APIVersions" do
    repeated :versions, :string, 1
    repeated :serverAddressByClientCIDRs, :message, 2, "k8s.io.apimachinery.pkg.apis.meta.v1.ServerAddressByClientCIDR"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Condition" do
    optional :type, :string, 1
    optional :status, :string, 2
    optional :observedGeneration, :int64, 3
    optional :lastTransitionTime, :message, 4, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
    optional :reason, :string, 5
    optional :message, :string, 6
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.CreateOptions" do
    repeated :dryRun, :string, 1
    optional :fieldManager, :string, 3
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.DeleteOptions" do
    optional :gracePeriodSeconds, :int64, 1
    optional :preconditions, :message, 2, "k8s.io.apimachinery.pkg.apis.meta.v1.Preconditions"
    optional :orphanDependents, :bool, 3
    optional :propagationPolicy, :string, 4
    repeated :dryRun, :string, 5
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Duration" do
    optional :duration, :int64, 1
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.FieldsV1" do
    optional :Raw, :bytes, 1
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GetOptions" do
    optional :resourceVersion, :string, 1
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GroupKind" do
    optional :group, :string, 1
    optional :kind, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GroupResource" do
    optional :group, :string, 1
    optional :resource, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersion" do
    optional :group, :string, 1
    optional :version, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionForDiscovery" do
    optional :groupVersion, :string, 1
    optional :version, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionKind" do
    optional :group, :string, 1
    optional :version, :string, 2
    optional :kind, :string, 3
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionResource" do
    optional :group, :string, 1
    optional :version, :string, 2
    optional :resource, :string, 3
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelector" do
    map :matchLabels, :string, :string, 1
    repeated :matchExpressions, :message, 2, "k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement" do
    optional :key, :string, 1
    optional :operator, :string, 2
    repeated :values, :string, 3
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.List" do
    optional :metadata, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta"
    repeated :items, :message, 2, "k8s.io.apimachinery.pkg.runtime.RawExtension"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta" do
    optional :selfLink, :string, 1
    optional :resourceVersion, :string, 2
    optional :continue, :string, 3
    optional :remainingItemCount, :int64, 4
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.ListOptions" do
    optional :labelSelector, :string, 1
    optional :fieldSelector, :string, 2
    optional :watch, :bool, 3
    optional :allowWatchBookmarks, :bool, 9
    optional :resourceVersion, :string, 4
    optional :resourceVersionMatch, :string, 10
    optional :timeoutSeconds, :int64, 5
    optional :limit, :int64, 7
    optional :continue, :string, 8
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry" do
    optional :manager, :string, 1
    optional :operation, :string, 2
    optional :apiVersion, :string, 3
    optional :time, :message, 4, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
    optional :fieldsType, :string, 6
    optional :fieldsV1, :message, 7, "k8s.io.apimachinery.pkg.apis.meta.v1.FieldsV1"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.MicroTime" do
    optional :seconds, :int64, 1
    optional :nanos, :int32, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta" do
    optional :name, :string, 1
    optional :generateName, :string, 2
    optional :namespace, :string, 3
    optional :selfLink, :string, 4
    optional :uid, :string, 5
    optional :resourceVersion, :string, 6
    optional :generation, :int64, 7
    optional :creationTimestamp, :message, 8, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
    optional :deletionTimestamp, :message, 9, "k8s.io.apimachinery.pkg.apis.meta.v1.Time"
    optional :deletionGracePeriodSeconds, :int64, 10
    map :labels, :string, :string, 11
    map :annotations, :string, :string, 12
    repeated :ownerReferences, :message, 13, "k8s.io.apimachinery.pkg.apis.meta.v1.OwnerReference"
    repeated :finalizers, :string, 14
    optional :clusterName, :string, 15
    repeated :managedFields, :message, 17, "k8s.io.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.OwnerReference" do
    optional :apiVersion, :string, 5
    optional :kind, :string, 1
    optional :name, :string, 3
    optional :uid, :string, 4
    optional :controller, :bool, 6
    optional :blockOwnerDeletion, :bool, 7
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata" do
    optional :metadata, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadataList" do
    optional :metadata, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta"
    repeated :items, :message, 2, "k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata"
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Patch" do
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.PatchOptions" do
    repeated :dryRun, :string, 1
    optional :force, :bool, 2
    optional :fieldManager, :string, 3
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Preconditions" do
    optional :uid, :string, 1
    optional :resourceVersion, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.RootPaths" do
    repeated :paths, :string, 1
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.ServerAddressByClientCIDR" do
    optional :clientCIDR, :string, 1
    optional :serverAddress, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Status" do
    optional :metadata, :message, 1, "k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta"
    optional :status, :string, 2
    optional :message, :string, 3
    optional :reason, :string, 4
    optional :details, :message, 5, "k8s.io.apimachinery.pkg.apis.meta.v1.StatusDetails"
    optional :code, :int32, 6
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.StatusCause" do
    optional :reason, :string, 1
    optional :message, :string, 2
    optional :field, :string, 3
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.StatusDetails" do
    optional :name, :string, 1
    optional :group, :string, 2
    optional :kind, :string, 3
    optional :uid, :string, 6
    repeated :causes, :message, 4, "k8s.io.apimachinery.pkg.apis.meta.v1.StatusCause"
    optional :retryAfterSeconds, :int32, 5
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.TableOptions" do
    optional :includeObject, :string, 1
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Time" do
    optional :seconds, :int64, 1
    optional :nanos, :int32, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Timestamp" do
    optional :seconds, :int64, 1
    optional :nanos, :int32, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.TypeMeta" do
    optional :kind, :string, 1
    optional :apiVersion, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.UpdateOptions" do
    repeated :dryRun, :string, 1
    optional :fieldManager, :string, 2
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.Verbs" do
    repeated :items, :string, 1
  end
  add_message "k8s.io.apimachinery.pkg.apis.meta.v1.WatchEvent" do
    optional :type, :string, 1
    optional :object, :message, 2, "k8s.io.apimachinery.pkg.runtime.RawExtension"
  end
end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Apis
          module Meta
            module V1
              APIGroup = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.APIGroup").msgclass
              APIGroupList = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.APIGroupList").msgclass
              APIResource = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.APIResource").msgclass
              APIResourceList = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.APIResourceList").msgclass
              APIVersions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.APIVersions").msgclass
              Condition = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Condition").msgclass
              CreateOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.CreateOptions").msgclass
              DeleteOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.DeleteOptions").msgclass
              Duration = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Duration").msgclass
              FieldsV1 = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.FieldsV1").msgclass
              GetOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GetOptions").msgclass
              GroupKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GroupKind").msgclass
              GroupResource = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GroupResource").msgclass
              GroupVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersion").msgclass
              GroupVersionForDiscovery = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionForDiscovery").msgclass
              GroupVersionKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionKind").msgclass
              GroupVersionResource = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.GroupVersionResource").msgclass
              LabelSelector = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelector").msgclass
              LabelSelectorRequirement = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement").msgclass
              List = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.List").msgclass
              ListMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta").msgclass
              ListOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.ListOptions").msgclass
              ManagedFieldsEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry").msgclass
              MicroTime = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.MicroTime").msgclass
              ObjectMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta").msgclass
              OwnerReference = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.OwnerReference").msgclass
              PartialObjectMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata").msgclass
              PartialObjectMetadataList = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadataList").msgclass
              Patch = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Patch").msgclass
              PatchOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.PatchOptions").msgclass
              Preconditions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Preconditions").msgclass
              RootPaths = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.RootPaths").msgclass
              ServerAddressByClientCIDR = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.ServerAddressByClientCIDR").msgclass
              Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Status").msgclass
              StatusCause = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.StatusCause").msgclass
              StatusDetails = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.StatusDetails").msgclass
              TableOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.TableOptions").msgclass
              Time = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Time").msgclass
              Timestamp = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Timestamp").msgclass
              TypeMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.TypeMeta").msgclass
              UpdateOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.UpdateOptions").msgclass
              Verbs = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.Verbs").msgclass
              WatchEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("k8s.io.apimachinery.pkg.apis.meta.v1.WatchEvent").msgclass
            end
          end
        end
      end
    end
  end
end
