# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/apimachinery/pkg/runtime/schema/generated.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
end

module K8s
  module Io
    module Apimachinery
      module Pkg
        module Runtime
          module Schema
          end
        end
      end
    end
  end
end
